name: 'todo_frontend'

on:
  push:
    branches:
      - master

jobs:
  push_to_Docker_Hub:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: setup env
        run: |
          export BACKEND_URL=${{ secrets.BACKEND_URL }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USER }}/projects:todo_frontend
          build-args: BACKEND_URL=${{ secrets.BACKEND_URL }}

  deploy:
    runs-on: [self-hosted, linux, x64]
    needs: [push_to_Docker_Hub]
    steps:
      - name: pull image in workers
        run: |
          /home/ubuntu/todo_frontend/deploy-to-swarm.sh
      - name: pull the compose file in manager
        run: |
          /home/ubuntu/todo_frontend/docker-start.sh
